### ISSUE TITLE
Agregar la configuración en el archivo application.properties

### ISSUE THREAD

**Issue by HectorC23** [GastonT800/trabajo_practico_4#20]
Agregar esto  application.properties:

spring.datasource.url=jdbc:mysql://localhost:3306/tp_final_bd?ServerTimezone=UTC
spring.datasource.username=root
spring.datasource.password=visual2024
spring.jpa.open-in-view = true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto= create

**Comment by mili-08** [comment]
Task finalizadas: 

    - Creación de la Base de Datos "tp_final_bd" 
    - Configuración del application.properties para la conexion a la bd terminado.
