### ISSUE TITLE
MateriaRepository

### ISSUE THREAD

**Issue by GastonT800** [GastonT800/trabajo_practico_4#23]
Implementar la interfaz MateriaRepository que extiende JpaRepository. 
Esta interfaz debe proporcionar métodos para realizar operaciones CRUD (crear, leer, actualizar y eliminar) relacionadas con las entidades de la materia. 
Además, se espera que integre funcionalidades específicas:

Relación con Carrera:
Agregar métodos para recuperar todas las materias asociadas a una carrera específica.
Permitir la búsqueda de materias por nombre o código dentro de una carrera.
Relación con Docente:
Incluir métodos para obtener todas las materias asignadas a un docente en particular.
Facilitar la búsqueda de materias por nombre o código relacionadas con un docente.
Requisitos de la base de datos:
Asegurarse de que los métodos implementados cumplan con las restricciones y relaciones definidas en el modelo de datos.
Considerar la eficiencia y la optimización de consultas para mejorar el rendimiento.

**Comment by mili-08** [comment]
- Materia Repository métodos funcionales.
