### ISSUE TITLE
Validaciones Materia

### ISSUE THREAD

**Issue by GastonT800** [GastonT800/trabajo_practico_4#34]
Se requiere implementar validaciones completas en la gestión de materias para garantizar la integridad de los datos ingresados por los usuarios y asegurar una correcta relación con otras entidades, como carrera y docente. Las acciones específicas a realizar son:

Integración de base de datos : Establecer conexion con la base de datos y gestionar los datos de carreras y docentes.

Validación de referencia: Desarrollar lógica de validación para verificar la existencia de las relaciones con carreras y docentes al crear o modificar una materia.

Validación de datos de entrada: Implementar validaciones con el formato adecuado y con todos los campos obligatorios del formulario de alta y modificacion de materias.

Pruebas funcionales : Realizar pruebas de casos límite y datos incorrectos, garantizando respuestas adecuadas del sistema y mensajes claros de retroalimentación para los usuarios.

**Comment by mili-08** [comment]
- Validaciones implementadas correctamente.
